behaviors:
  Builder:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 160000
      learning_rate: 0.0002
      beta: 0.01
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.90
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 5.0e10
    time_horizon: 1000
    summary_freq: 12000
    threaded: true