behaviors:
  TestBehavior3:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 24000
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.15
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.90
        strength: 1.5
    keep_checkpoints: 10
    max_steps: 5.0e7
    time_horizon: 1000
    summary_freq: 12000
    threaded: true